### ISSUE TITLE
Bonemeal not working cant find away to get it back

### ISSUE THREAD

**Issue by Scrincz** [lishaodong/Syndria#7]
bonemeal wont work, ive searched through world guard and found out no information on why it was not working

**Comment by Scrincz** [comment]
I think it might be disabled due to dr making it so you could not get seeds so you could not grow your
own food but idk where in the code to find that

**Comment by lishaodong** [comment]
I tried bonemeal for trees it work. you need to click four times seems.

**Comment by lishaodong** [comment]
currently bonemeal on grass land not work?(what's the expect behavior? grow grass).
but bonemeal on grass make it double length.

now it can not remove the grass (single or double length). you can try remove the block under it then it disappear.
///////May because FatigueMach.java. line 492. I add isOp() condition still can't remove.

**Comment by lishaodong** [comment]
now find the problem.

RestrictionMach.java

line 734-744

also enable leave decay. block grow. block spread.

**Comment by lishaodong** [comment]
disable leave decay
